// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfK7lfRYtJTqXejnm2RVXoQFxoT2gh9r8',
    appId: '1:757884806403:web:a66474c6006f0618e2f536',
    messagingSenderId: '757884806403',
    projectId: 'majet-24',
    authDomain: 'majet-24.firebaseapp.com',
    storageBucket: 'majet-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuTlj1RI9QBfJ34sYPQkiC6c5gtV-c430',
    appId: '1:757884806403:android:3acdd982a8709743e2f536',
    messagingSenderId: '757884806403',
    projectId: 'majet-24',
    storageBucket: 'majet-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUlac9zpR3ami2Zi6NbjMXCsE_70ezAcY',
    appId: '1:757884806403:ios:838efe76af8e1cbfe2f536',
    messagingSenderId: '757884806403',
    projectId: 'majet-24',
    storageBucket: 'majet-24.appspot.com',
    iosClientId: '757884806403-np3knokjolnlmit4jvc9hob0gjm865cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUlac9zpR3ami2Zi6NbjMXCsE_70ezAcY',
    appId: '1:757884806403:ios:838efe76af8e1cbfe2f536',
    messagingSenderId: '757884806403',
    projectId: 'majet-24',
    storageBucket: 'majet-24.appspot.com',
    iosClientId: '757884806403-np3knokjolnlmit4jvc9hob0gjm865cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
