// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgYeM-4MnRLgRMna2ifQYdzWgdYezEpPM',
    appId: '1:829279422329:web:a001af1828ad91153151a8',
    messagingSenderId: '829279422329',
    projectId: 'fooddelivery-689ff',
    authDomain: 'fooddelivery-689ff.firebaseapp.com',
    databaseURL: 'https://fooddelivery-689ff-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-689ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZXfhpsL950iiWM_pvmqWF84Bckec7c0w',
    appId: '1:829279422329:android:47ed5fd67874a6833151a8',
    messagingSenderId: '829279422329',
    projectId: 'fooddelivery-689ff',
    databaseURL: 'https://fooddelivery-689ff-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-689ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhjsSwcYycn07gnM9b6n-K2E-ynCYx7o0',
    appId: '1:829279422329:ios:33e99935f97f6ccb3151a8',
    messagingSenderId: '829279422329',
    projectId: 'fooddelivery-689ff',
    databaseURL: 'https://fooddelivery-689ff-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-689ff.appspot.com',
    iosClientId: '829279422329-8ac2tck4kkgqicqhthsqjlr7ie3gfkhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhjsSwcYycn07gnM9b6n-K2E-ynCYx7o0',
    appId: '1:829279422329:ios:33e99935f97f6ccb3151a8',
    messagingSenderId: '829279422329',
    projectId: 'fooddelivery-689ff',
    databaseURL: 'https://fooddelivery-689ff-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-689ff.appspot.com',
    iosClientId: '829279422329-8ac2tck4kkgqicqhthsqjlr7ie3gfkhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
