// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHlngws9HA0vmciPwe4oLol9KILaurKkQ',
    appId: '1:922524715807:web:31c0cfb446739208ffbe2a',
    messagingSenderId: '922524715807',
    projectId: 'fooddelivery-95ad8',
    authDomain: 'fooddelivery-95ad8.firebaseapp.com',
    databaseURL: 'https://fooddelivery-95ad8-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-95ad8.appspot.com',
    measurementId: 'G-KMQMDJDKER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZCYE1lt857FzKhJneuS3Ac7LZgCiFzS4',
    appId: '1:922524715807:android:beeb82ff53a93767ffbe2a',
    messagingSenderId: '922524715807',
    projectId: 'fooddelivery-95ad8',
    databaseURL: 'https://fooddelivery-95ad8-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-95ad8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCmfMMpyp_5zBzwu20O57aXG_5Y2R5zNg',
    appId: '1:922524715807:ios:8a2cb6f4d9789915ffbe2a',
    messagingSenderId: '922524715807',
    projectId: 'fooddelivery-95ad8',
    databaseURL: 'https://fooddelivery-95ad8-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-95ad8.appspot.com',
    iosClientId: '922524715807-dmq4ge9onv1eridmqu5e0tlf80ef8c8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCmfMMpyp_5zBzwu20O57aXG_5Y2R5zNg',
    appId: '1:922524715807:ios:8a2cb6f4d9789915ffbe2a',
    messagingSenderId: '922524715807',
    projectId: 'fooddelivery-95ad8',
    databaseURL: 'https://fooddelivery-95ad8-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-95ad8.appspot.com',
    iosClientId: '922524715807-dmq4ge9onv1eridmqu5e0tlf80ef8c8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
